import { DialogueNode } from '../types/game';

export const GAME_DIALOGUES: Record<string, DialogueNode> = {
  // --- PROLOGUE & KIKI ---
  intro_start: {
    id: 'intro_start',
    speaker: 'Narator Cerita',
    speakerRole: 'Lembah Nada Rasa',
    portrait: 'narrator',
    text: 'Langit bergemuruh pelan... Tiba-tiba kabut abu-abu pekat turun menyelimuti Lembah Nada Rasa! Air mancur terhenti, dan warna-warni bunga seketika memudar menjadi kelabu.',
    nextId: 'intro_start_2',
  },
  intro_start_2: {
    id: 'intro_start_2',
    speaker: 'Rian / Tara',
    speakerRole: 'Murid Kelas 4',
    portrait: 'player',
    text: 'Hah?! Apa yang terjadi pada desa kita? Lihat, ada benda berkilau yang jatuh di depanku... ini seperti Kompas Kristal bertuliskan "KOMPAS HATI"!',
    nextId: 'intro_start_3',
  },
  intro_start_3: {
    id: 'intro_start_3',
    speaker: 'Pesan Rahasia Kompas',
    speakerRole: 'Pusaka Lembah',
    portrait: 'compass_item',
    text: '"Warna dunia memudar saat hati terkunci oleh salah paham. Gunakan Kompas Resonansi untuk membaca perasaan sejati yang tersembunyi di balik kata-kata!"',
    choices: [
      {
        id: 'c_start_help',
        text: 'Tekan Kompas dan hampiri Kiki si Tupai!',
        impactScore: 10,
        resultDialogueId: 'kiki_wait',
      },
    ],
  },
  kiki_wait: {
    id: 'kiki_wait',
    speaker: 'Petunjuk Awal',
    speakerRole: 'Misi Pertama',
    portrait: 'narrator',
    text: 'Kiki si tupai pos melompat panik di sebelah kiri air mancur! Dekati dia lalu tekan tombol [RESONANSI EMOSI] untuk membaca apa yang sedang dirasakannya.',
  },

  // Kiki dialogue
  kiki_intro: {
    id: 'kiki_intro',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Ciiit! Gawat! Bencana besar! Surat-surat kiriman warga terbang tertiup angin kabut! Aku... aku pasti akan dimarahi! Semua orang akan membenciku!',
    thoughtBubble: 'Jantungku berdegup kencang sekali, nafasku rasanya sesak... aku takut gagal!',
    emotionAura: 'cemas',
    choices: [
      {
        id: 'c_kiki_1',
        text: 'Tenang Kiki, jangan teriak-teriak begitu, bikin pusing!',
        impactScore: -5,
        resultDialogueId: 'kiki_dismiss',
      },
      {
        id: 'c_kiki_2',
        text: 'Kiki, tarik napas dulu bersamaku. Mari gunakan Teknik Napas Balon!',
        impactScore: 15,
        resultDialogueId: 'kiki_breathe_prep',
      },
      {
        id: 'c_kiki_3',
        text: 'Wajar kamu merasa panik, tapi surat yang jatuh bisa kita kumpulkan bersama.',
        impactScore: 10,
        resultDialogueId: 'kiki_validate',
      },
    ],
  },
  kiki_dismiss: {
    id: 'kiki_dismiss',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Huuu... kamu malah menyalahkanku! Aku semakin gemetar...',
    nextId: 'kiki_intro',
  },
  kiki_validate: {
    id: 'kiki_validate',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Kamu... kamu tidak memarahiku? Tapi dadaku masih berdebar kencang sekali... rasanya seperti mau meledak.',
    nextId: 'kiki_breathe_prep',
  },
  kiki_breathe_prep: {
    id: 'kiki_breathe_prep',
    speaker: 'Rian / Tara',
    speakerRole: 'Murid Kelas 4',
    portrait: 'player',
    text: 'Ingat pelajaran di sekolah, Kiki! Tarik napas lewat hidung 4 detik, bayangkan meniup balon di perut, tahan sebentar, lalu hembuskan perlahan.',
    triggerBreathing: true,
    nextId: 'kiki_after_breathe',
  },
  kiki_after_breathe: {
    id: 'kiki_after_breathe',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Fiuuuh... ajaib! Detak jantungku mulai melambat. Otakku terasa lebih jernih sekarang! Terima kasih sudah menemaniku bernapas!',
    triggerColorRestoreZone: 'plaza',
    triggerQuestProgress: 'quest_start',
    nextId: 'kiki_reward',
  },
  kiki_reward: {
    id: 'kiki_reward',
    speaker: 'Kiki',
    speakerRole: 'Tupai Pos Cilik',
    portrait: 'squirrel',
    text: 'Lihat! Air mancur plaza kembali memancarkan air jernih dan warna rumput di sekitar kita kembali hijau bersinar! Ini "Surat Wasiat Kuno" yang kutemukan, sepertinya penting untuk Kakek Ranu di Jembatan!',
    givesItem: 'item_letter',
  },

  // --- KAKEK RANU & JEMBATAN (BRANCHING IMPACTFUL CHOICE) ---
  ranu_intro: {
    id: 'ranu_intro',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'GRRR! Mau apa kalian bocah-bocah berisik?! Jembatan ini KUTUTUP! Pulang sana! Kalian cuma tahu main-main dan bikin rusak desa!',
    thoughtBubble: 'Semua orang hanya datang padaku saat ada yang rusak... Begitu tua dan lamban, aku ditinggalkan sendirian...',
    emotionAura: 'marah',
    choices: [
      {
        id: 'ranu_c1',
        text: 'Pilihan A: Validasi Rasa Sepi (Kakek pasti lelah bekerja sendiri... Kami sangat menghargai jasa Kakek).',
        impactScore: 20,
        resultDialogueId: 'ranu_path_empathy',
        branchTag: 'empathy_first',
      },
      {
        id: 'ranu_c2',
        text: 'Pilihan B: Solusi Logis & Jujur (Kakek, Bimo kehilangan roda gigi jam desa. Tolong buka jembatan agar kami bisa selesaikan bersama).',
        impactScore: 15,
        resultDialogueId: 'ranu_path_logic',
        branchTag: 'logic_first',
      },
      {
        id: 'ranu_c3',
        text: 'Kakek jahat! Jangan galak-galak begitu dong, nanti cepat tua!',
        impactScore: -10,
        resultDialogueId: 'ranu_angry_rebuke',
      },
    ],
  },
  ranu_angry_rebuke: {
    id: 'ranu_angry_rebuke',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'KAU BILANG APA?! Tidak punya sopan santun! Pergi dari jembatanku sebelum kuhalau dengan gagang sapu!',
    nextId: 'ranu_intro',
  },
  ranu_path_empathy: {
    id: 'ranu_path_empathy',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'A... apa katamu tadi? Kalian... menghargaiku? (Kakek Ranu mengusap sudut matanya). Sudah bertahun-tahun tidak ada yang menanyakan kabarku selain meminta jembatan dibetulkan...',
    nextId: 'ranu_path_empathy_2',
  },
  ranu_path_empathy_2: {
    id: 'ranu_path_empathy_2',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Maafkan Kakek yang membentak tadi. Rasa marah ini sebenarnya karena Kakek merasa kesepian dan takut tidak berguna lagi. Nih, jembatan kubuka lebar-lebar!',
    triggerColorRestoreZone: 'bridge',
    triggerQuestProgress: 'quest_bridge',
    givesItem: 'item_secret_key',
    nextId: 'ranu_path_empathy_3',
  },
  ranu_path_empathy_3: {
    id: 'ranu_path_empathy_3',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Sebagai tanda terima kasih karena telah mendengar hatiku, bawalah "Kunci Kuno Gudang Arsip" ini. Dan satu rahasia: Pohon Suci di Hutan Utara menyukai doa ketulusan!',
  },

  ranu_path_logic: {
    id: 'ranu_path_logic',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Hmm... Jadi si kecil Bimo sedang kebingungan mencari roda gigi jam? Anak itu memang berbakat, tapi sering terlalu keras pada dirinya sendiri...',
    nextId: 'ranu_path_logic_2',
  },
  ranu_path_logic_2: {
    id: 'ranu_path_logic_2',
    speaker: 'Kakek Ranu',
    speakerRole: 'Tukang Kayu Desa',
    portrait: 'old_man',
    text: 'Baiklah! Jembatan kubuka. Tapi berjanjilah, sampaikan pada Bimo bahwa berbuat salah itu manusiawi, yang terpenting adalah berani belajar memperbaikinya!',
    triggerColorRestoreZone: 'bridge',
    triggerQuestProgress: 'quest_bridge',
    givesItem: 'item_bridge_pass',
  },

  // --- BIMO DI HUTAN SUNYI ---
  bimo_intro: {
    id: 'bimo_intro',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: '(Sesenggukan di balik pohon)... Huwaaa! Aku ceroboh sekali! Roda gigi jam desa jatuh ke semak-semak dan sekarang jamnya mati. Aku pantas dijauhi semua orang...',
    thoughtBubble: 'Pasti semua teman menertawakanku... aku merasa sangat malu dan tak berharga...',
    emotionAura: 'sedih',
    choices: [
      {
        id: 'bimo_c1',
        text: 'Bimo, satu kesalahan tidak membuatmu jadi anak yang buruk. Kita cari solusinya bersama!',
        impactScore: 20,
        resultDialogueId: 'bimo_growth_mindset',
      },
      {
        id: 'bimo_c2',
        text: 'Tenang saja, Kakek Ranu sudah memaafkanmu dan justru memujimu berbakat!',
        impactScore: 15,
        resultDialogueId: 'bimo_ranu_praise',
      },
      {
        id: 'bimo_c3',
        text: 'Kamu sih kurang hati-hati! Makanya kalau pegang barang penting jangan melamun!',
        impactScore: -10,
        resultDialogueId: 'bimo_shame',
      },
    ],
  },
  bimo_shame: {
    id: 'bimo_shame',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Huwaaa! Benar kan kataku... aku memang selalu merusak segalanya!',
    nextId: 'bimo_intro',
  },
  bimo_ranu_praise: {
    id: 'bimo_ranu_praise',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Be... benarkah? Kakek Ranu tidak marah padaku? Padahal tadi aku takut sekali sampai lututku lemas...',
    nextId: 'bimo_growth_mindset',
  },
  bimo_growth_mindset: {
    id: 'bimo_growth_mindset',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Perkataanmu benar... Guru di kelas selalu mengingatkan tentang "Growth Mindset" (Pola Pikir Berkembang): Kesalahan adalah bukti bahwa kita sedang berusaha!',
    nextId: 'bimo_growth_mindset_2',
  },
  bimo_growth_mindset_2: {
    id: 'bimo_growth_mindset_2',
    speaker: 'Bimo',
    speakerRole: 'Murid Kelas 4',
    portrait: 'boy_glasses',
    text: 'Ini dia! Aku berhasil menyelamatkan "Roda Gigi Emas Pusaka"! Bawalah ke Menara Jam di timur laut. Mari kembalikan dentang waktu dan warna desa kita!',
    triggerColorRestoreZone: 'forest',
    triggerQuestProgress: 'quest_bimo',
    givesItem: 'item_gold_gear',
  },

  // --- PROFESOR KOTEK (RAHASIA & MOMEN LUCU) ---
  kotek_intro: {
    id: 'kotek_intro',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'KUKU-RUYUK! Kroscek data kardiak! Selamat datang di pos pengamatan ayam tercerdas se-Lembah Nada Rasa!',
    thoughtBubble: 'Kacamata bulatku keren kan? Jangan sampai tahu kalau aku suka mematok cacing!',
    emotionAura: 'gembira',
    choices: [
      {
        id: 'kotek_c1',
        text: 'Halo Profesor! Apa yang sedang kamu teliti di sini?',
        impactScore: 10,
        resultDialogueId: 'kotek_fact',
      },
      {
        id: 'kotek_c2',
        text: 'Wah, ayam pakai kacamata?! Lucu sekali!',
        impactScore: 10,
        resultDialogueId: 'kotek_funny',
      },
    ],
  },
  kotek_funny: {
    id: 'kotek_funny',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'Eits, jangan salah! Kacamata ini berlensa fokus empati! Nah, karena kamu tersenyum melihatku, kamu baru saja melepaskan hormon Oksitosin dan Endorfin yang membuat tubuh rileks!',
    nextId: 'kotek_fact',
  },
  kotek_fact: {
    id: 'kotek_fact',
    speaker: 'Profesor Kotek',
    speakerRole: 'Ayam Saintis Emosi',
    portrait: 'chicken_glasses',
    text: 'Fakta Sains PSE: Saat manusia merasa marah atau panik, Otak Amigdala menyala seperti alarm kebakaran. Satu pelukan atau tawa ramah bisa mematikan alarm itu seketika! Ambil "Lencana Telur Ceria" ini!',
    givesItem: 'item_egg_badge',
  },

  // --- POHON RAHASIA (SECRET TREE) ---
  secret_tree: {
    id: 'secret_tree',
    speaker: 'Pohon Sahabat Purba',
    speakerRole: 'Rahasia Tersembunyi Hutan',
    portrait: 'tree',
    text: 'Dedaunan pohon purba ini berdesir lembut... Di celah akarnya yang dilapisi lumut keemasan, tersimpan sebuah Kapsul Waktu Tahun 1950.',
    choices: [
      {
        id: 'st_open',
        text: 'Buka Kapsul Waktu dengan niat persahabatan',
        impactScore: 15,
        resultDialogueId: 'secret_tree_capsule',
      },
    ],
  },
  secret_tree_capsule: {
    id: 'secret_tree_capsule',
    speaker: 'Pesan Kapsul Waktu 1950',
    speakerRole: 'Surat Pendiri Desa',
    portrait: 'scroll',
    text: '"Wahai anak masa depan: Bila kabut kesalahpahaman menutupi desamu, ingatlah tiga kata ajaib: Tolong, Maaf, dan Terima Kasih. Mendengarkan adalah hadiah terbesar bagi sesama manusia."',
    givesItem: 'item_friendship_capsule',
  },

  // --- CLIMAX AT THE CLOCK TOWER (PLOT TWIST: NENEK WILIS) ---
  tower_intro: {
    id: 'tower_intro',
    speaker: 'Sosok Misterius Kabut',
    speakerRole: 'Bayangan Menara',
    portrait: 'spirit_elder',
    text: 'Berhenti di sana... Mengapa kalian repot-repot memulihkan warna desa ini? Bukankah manusia hanya peduli pada kesibukannya masing-masing?',
    thoughtBubble: 'Aku lelah... bertahun-tahun di perpustakaan, melihat warga semakin sering berteriak dan saling menyakiti tanpa mau mendengar...',
    emotionAura: 'kecewa',
    choices: [
      {
        id: 'tw_c1',
        text: 'Siapa kamu sebenarnya? Apakah kamu monster pembuat kabut abu-abu?',
        impactScore: 5,
        resultDialogueId: 'tower_reveal',
      },
      {
        id: 'tw_c2',
        text: 'Kami datang bukan untuk bertengkar. Kompas kami merasakan rasa sedih yang sangat dalam di hatimu.',
        impactScore: 25,
        resultDialogueId: 'tower_empathy_twist',
      },
    ],
  },
  tower_reveal: {
    id: 'tower_reveal',
    speaker: 'Sosok Misterius Kabut',
    speakerRole: 'Bayangan Menara',
    portrait: 'spirit_elder',
    text: 'Monster? Haha... lihatlah lebih dekat dengan Kompas Hati kalian!',
    nextId: 'tower_empathy_twist',
  },
  tower_empathy_twist: {
    id: 'tower_empathy_twist',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: '(Kabut menipis memperlihatkan seorang nenek tua berpakaian ramah dengan selendang batik). Namaku Wilis. Aku bukan monster. Kabut abu-abu ini adalah wujud nyata dari kata-kata pedas dan prasangka yang menumpuk di desa kita...',
    nextId: 'tower_twist_explanation',
  },
  tower_twist_explanation: {
    id: 'tower_twist_explanation',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Ketika orang-orang berhenti bertanya "Apa yang sedang kamu rasakan?", kristal jam waktu membeku. Tapi... kalian berhasil mendengarkan Kiki, memahami luka Kakek Ranu, dan mendampingi Bimo!',
    nextId: 'tower_final_choice',
  },
  tower_final_choice: {
    id: 'tower_final_choice',
    speaker: 'Nenek Wilis',
    speakerRole: 'Pustakawan Sepuh Desa',
    portrait: 'grandmother',
    text: 'Kini Roda Gigi Emas ada di tanganmu. Pilihan terakhir ada padamu: Pesan apa yang ingin kau canangkan saat lonceng harmoni berdentang?',
    choices: [
      {
        id: 'choice_ending_perfect',
        text: '"Pesan Empati": Mari kita deklarasikan Desa Pendengar Hati, di mana setiap perasaan diakui dan dihargai!',
        impactScore: 30,
        resultDialogueId: 'ending_perfect_scene',
      },
      {
        id: 'choice_ending_resilient',
        text: '"Pesan Keberanian": Mengakui kesalahan dan memaafkan adalah kekuatan sejati anak-anak Lembah!',
        impactScore: 25,
        resultDialogueId: 'ending_resilient_scene',
      },
    ],
  },
  ending_perfect_scene: {
    id: 'ending_perfect_scene',
    speaker: 'Lonceng Menara Jam',
    speakerRole: 'Harmoni Lembah',
    portrait: 'bell_tower',
    text: 'DIIING... DOOONG! Dentang lonceng menara menggetarkan seluruh lembah! Gelombang cahaya emas pelangi menyapu setiap sudut tanah, memulihkan seluruh warna dunia 100%!',
    triggerColorRestoreZone: 'tower',
    triggerQuestProgress: 'quest_tower',
    nextId: 'ending_summary_perfect',
  },
  ending_resilient_scene: {
    id: 'ending_resilient_scene',
    speaker: 'Lonceng Menara Jam',
    speakerRole: 'Harmoni Lembah',
    portrait: 'bell_tower',
    text: 'DIIING... DOOONG! Suara dentang hangat menembus kabut! Pohon-pohon bersemi bunga warna-warni, burung berkicau, dan warga keluar rumah sambil tersenyum saling merangkul!',
    triggerColorRestoreZone: 'tower',
    triggerQuestProgress: 'quest_tower',
    nextId: 'ending_summary_resilient',
  },
  ending_summary_perfect: {
    id: 'ending_summary_perfect',
    speaker: 'Nenek Wilis & Seluruh Warga',
    speakerRole: 'Pesta Harmoni',
    portrait: 'celebration',
    text: 'Selamat! Berkat kebijaksanaan dan empati kalian, Lembah Nada Rasa kembali hidup penuh warna! Kamu telah dianugerahi gelar: "DUTA EMPATI EMAS KELAS 4 SD"!',
  },
  ending_summary_resilient: {
    id: 'ending_summary_resilient',
    speaker: 'Nenek Wilis & Seluruh Warga',
    speakerRole: 'Pesta Harmoni',
    portrait: 'celebration',
    text: 'Luar biasa! Lembah telah pulih dari kabut prasangka. Semua warga belajar bahwa mendengar dan memaafkan adalah kunci kedamaian. Kamu dianugerahi gelar: "PENJELAJAH HATI TANGGUH"!',
  },
};
